### ISSUE TITLE
submodule update xml

### ISSUE THREAD

**Issue by sonoro1234** [lubyk/lubyk#2]
I have done git pull for lubyk then submodule update:

fatal: reference is not a tree: fc6c8e3163fbce1608c58a4a56dd08b4cd3e01eb
Unable to checkout 'fc6c8e3163fbce1608c58a4a56dd08b4cd3e01eb' in submodule path 'modules/xml'

**Comment by lubyk** [comment]
The whole lubyk project is actually out of sync and unusable because of module reorganisation and rewriting in order for each part to be usable without requiring all of lubyk. There was too much coupling between libraries and it made it difficult to release any part as a separate, documented project.

**Comment by sonoro1234** [comment]
thas great!! I have always thought that would be better to get isolated modules. I will come back to this page waiting reorganization is finished.
I was interested in trying four but with wxLua or iup intead of mimas? (I dont know what is mimas exactly)
I dont know if there is also any sound moldule in lubyk
Best
victor bombi
